# Generated by Django 5.1 on 2024-09-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmember',
            name='user',
        ),
    ]
