# Generated by Django 5.1 on 2024-09-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0002_remove_labmember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryexit',
            name='exit_time',
        ),
        migrations.AddField(
            model_name='entryexit',
            name='is_entry',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
