# Generated by Django 5.1 on 2024-09-03 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0003_remove_entryexit_exit_time_entryexit_is_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
