# Generated by Django 5.1 on 2024-09-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0004_labmember_last_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlystay',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlystay',
            name='member',
        ),
        migrations.AddField(
            model_name='labmember',
            name='average_daily_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='labmember',
            name='last_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmember',
            name='month_first_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labmember',
            name='monthly_entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labmember',
            name='monthly_total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EntryExit',
        ),
        migrations.DeleteModel(
            name='MonthlyStay',
        ),
    ]
