# Generated by Django 5.1 on 2024-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0005_alter_monthlystay_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('entry_count', models.IntegerField()),
                ('average_daily_time', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_archives', to='labstatus.labmember')),
            ],
            options={
                'unique_together': {('member', 'year', 'month')},
            },
        ),
    ]
