# Generated by Django 5.1 on 2024-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labstatus', '0006_monthlyarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='monthly_total_time',
            field=models.FloatField(default=0),
        ),
    ]
